### ISSUE TITLE
Different picture.

### ISSUE THREAD

**Issue by Dowtcom** [Skinz3/Symbioz#10]
Why is there a different picture on the github page? There is one picture that has the "huppermage" class.

**Comment by nojo123** [comment]
Hey Dowtcom, i think you haven't realized that this project hasn't been updated for over 4 months now. This is because Skinz has been working on this privately as he will be selling the server files. Huppermages are in the versions he is keeping private right now. This explains the "teaser" pictures he posted.

**Comment by Dowtcom** [comment]
I think you haven't realized this is a 2.30 release, not a "teaser" release. 
Closing this because I dont wan't any other retards taking my "Issue" out of context.

**Comment by nojo123** [comment]
The way you react is lame and unnecessary. I think i was quite clear about the pictures being a teaser for his next releases he will be selling. I never said his current 2.30 release was a teaser, the only person who is a retard right now is yourself.

**Comment by Skinz3** [comment]
nojo123 is right, i am working on a 2.34 private version

**Comment by nojo123** [comment]
Hey Skinz great to hear from you! Is there any chance you fix some bugs at this emulator (2.30)?

**Comment by Skinz3** [comment]
Not really, im not working anymore on this version, but.. what bug? :)

**Comment by nojo123** [comment]
Well one of the bugs are the "teleport" cells to get out of the bank. Would you be able to fix this easily or explain to me how i can do it myself?
