### ISSUE TITLE
One last quick question.

### ISSUE THREAD

**Issue by imnotacrook** [Skinz3/Symbioz#13]
Hey guys. I finally managed to get the server and game up and running. Now my remaining question is - Can I change the language to English? I haven't been able to find the option in game yet and I'm not sure if there's something I need to edit to get it to swap or if it's only available in French.

**Comment by nojo123** [comment]
Hey, 
I'm sorry to tell this but running your client in English will make it more buggy. The reason is is that the D2I file for English is probably missing and if its not alot of items and NPC's will be unusable or buggy. To fix it yourself will take alot of time. If you still want to use an English client you can change the language in the config.xml in your app folder where the Dofus.exe is located. Just search for FR and change it to EN. 

Best of luck, 
Nojo

**Comment by imnotacrook** [comment]
Thank you for that information. It sounds like I'll just have to deal with French seeing as I have no clue what I'm doing with this stuff haha.
